services:

  postgres:
    image: postgres:16-alpine
    container_name: cloud-file-storage-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: cloud-file-storage-app
#    ports:
#      - "8080:8080"
#    environment:
#      DB_URL: "jdbc:postgresql://postgres:5432/${POSTGRES_DB}"
#      DB_USERNAME: ${DB_USERNAME}
#      DB_PASSWORD: ${DB_PASSWORD}
#    depends_on:
#      - postgres
#    networks:
#      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:

