spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cloudfilestorage-db
    username: postgres
    password: 111
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: strict
      timeout: 30m

app:
  admin:
    name: "admin"
    password: "12345m"